package es.xproject.resizer;

import es.xproject.resizer.igu.Ventana;
import es.xproject.resizer.base.Constants;
import es.xproject.resizer.util.PropertiesUtil;
import it.sauronsoftware.junique.AlreadyLockedException;
import it.sauronsoftware.junique.JUnique;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static final org.apache.logging.log4j.Logger log = LogManager.getLogger();
    public static String version;
    public static String code;
    public static ResourceBundle rb;

    public String getGreeting() {
        return Constants.APPNAME;
    }

    public static void main(String[] args) {

        
        Ventana ventana = null;
        try {
            new PropertiesUtil().readVersion();
            Locale locale = Locale.getDefault();
            rb = ResourceBundle.getBundle("messages", locale);
            
            ventana = new Ventana();
            
            
            String appId = rb.getString("appId");
            JUnique.acquireLock(appId);
            
            ventana.setVisible(true);
        } catch (AlreadyLockedException ex) {
            log.error("AlreadyLockedException: La aplicación ya se está ejecutando");
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            if (ventana != null) {
                JOptionPane.showMessageDialog(ventana,
                        rb.getString("multipleInstance"),
                        Constants.APPNAME,
                        JOptionPane.ERROR_MESSAGE);
                ventana.dispose();
            }
            System.exit(0);
        }
    }

}
