package es.xproject.resizer;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "xProject Resizer";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Ventana v = new Ventana();
        v.setVisible(true);
    }
}
