package es.xproject.resizer;

import org.apache.logging.log4j.LogManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    private static final org.apache.logging.log4j.Logger log = LogManager.getLogger();
    
    public String getGreeting() {
        return "xProject Resizer";
    }

    public static void main(String[] args) {
        log.info(new App().getGreeting());
        
        Ventana v = new Ventana();
        v.setVisible(true);
    }
}
